# action.yml
name: 'AOCIntegTest'
description: 'AOCIntegTest performs end-to-end integration test on the AOCAgent'
inputs:
  running_type:
    description: 'running type'
    required: false
    default: 'ec2'
  agent_version:
    description: 'agent version'
    required: false
    default: "0.9.0"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.running_type }}"
    - "${{ inputs.agent_version }}"
