# action.yml
name: 'AOT-E2E'
description: 'AOT testing framework'
inputs:
  running_type:
    description: 'running type'
    required: false
    default: 'validator'
  opts:
    description: 'opts'
    required: false
    default: '-c default-validation.yml'
  platform:
    description: "testing platform: ec2, ecs, eks"
    required: false
    default: "ecs"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.running_type }}"
    - "${{ inputs.platform }}"
    - "${{ inputs.opts }}"